In [16]:
#层次聚类算法
from sklearn import datasets
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import pandas as pd
from sklearn.preprocessing import StandardScaler
BuddyMove = pd.read_csv('./buddymove_holidayiq.csv')
BMdata = BuddyMove.to_numpy()[:, :]
# transfer = StandardScaler()
# BMdata = transfer.fit_transform(BMdata)

#n_ clusters表示聚类个数, linkagea表示距高度量函数,其中ward是最小距离、 complete是最大距离、 average是平均距离
#测试不同的结果,只需替换一下就可以了
clustering = AgglomerativeClustering(linkage='ward', n_clusters=3)
res = clustering.fit(BMdata[:, 1:])
print("各个簇的样本数目:")
print(pd.Series(clustering.labels_).value_counts())
print("聚类结果:")
print(confusion_matrix(BMdata[:, 1],clustering. labels_))
plt.figure()
d0 = BMdata[clustering.labels_ == 0]
plt.plot(d0[:,0],d0[:,1],'r.')
d1 = BMdata[clustering. labels_ == 1]
plt.plot(d1[:,0],d1[:,1],'go')
d2 = BMdata[clustering. labels_ == 2]
plt.plot(d2[:,0],d2[:,1],'b*')
plt.xlabel( "Sepal. Length")
plt.ylabel("SepaL. Width")
plt.title("AGNES Clustering")
plt.show()

各个簇的样本数目:
0    132
1     86
2     31
dtype: int64
聚类结果:


ValueError: Classification metrics can't handle a mix of unknown and multiclass targets

In [6]:
BMdata

array([['User 1', 2, 77, ..., 69, 68, 95],
       ['User 2', 2, 62, ..., 76, 69, 68],
       ['User 3', 2, 50, ..., 87, 50, 75],
       ...,
       ['User 247', 20, 124, ..., 104, 158, 174],
       ['User 248', 20, 133, ..., 139, 144, 213],
       ['User 249', 20, 143, ..., 139, 159, 143]], dtype=object)

In [10]:
BMdata[:,1]

array([2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 4, 5, 4, 4,
       5, 4, 5, 5, 5, 5, 5, 5, 4, 5, 4, 4, 4, 4, 4, 5, 4, 4, 5, 5, 4, 4,
       5, 5, 4, 4, 5, 4, 14, 5, 4, 4, 8, 8, 6, 8, 8, 6, 8, 8, 8, 6, 8, 6,
       6, 6, 8, 8, 8, 8, 8, 8, 8, 6, 6, 6, 6, 6, 6, 6, 6, 8, 6, 6, 8, 8,
       6, 6, 8, 8, 8, 8, 6, 6, 8, 6, 8, 6, 8, 6, 8, 6, 6, 8, 8, 6, 12, 12,
       12, 12, 14, 14, 14, 12, 14, 12, 12, 12, 12, 12, 14, 14, 12, 14, 12,
       14, 12, 12, 14, 12, 12, 12, 14, 12, 12, 14, 12, 10, 12, 10, 12, 10,
       12, 14, 12, 10, 12, 12, 14, 14, 14, 12, 10, 12, 12, 14, 12, 12, 12,
       22, 14, 12, 12, 12, 22, 22, 16, 20, 20, 18, 20, 20, 22, 20, 18, 22,
       22, 18, 18, 18, 22, 20, 18, 18, 22, 20, 18, 22, 20, 18, 18, 18, 20,
       20, 22, 22, 22, 22, 25, 18, 22, 18, 18, 18, 16, 20, 16, 18, 18, 22,
       22, 18, 20, 18, 22, 18, 20, 18, 18, 18, 18, 18, 18, 18, 22, 22, 18,
       22, 18, 18, 25, 25, 25, 25, 25, 8, 22, 18, 20, 25, 18, 25, 18, 22,
       20, 20, 20], dtype=object)

In [7]:
iris = datasets.load_iris()
irisdata = iris.data

In [8]:
irisdata

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
iris


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [11]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])